/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppParametresRouteImport } from './routes/_app.parametres'
import { Route as AppMouvementsRouteImport } from './routes/_app.mouvements'
import { Route as AppFournisseursRouteImport } from './routes/_app.fournisseurs'
import { Route as AppBdcRouteImport } from './routes/_app.bdc'
import { Route as AppAffairesRouteImport } from './routes/_app.affaires'
import { Route as AppCatalogueIndexRouteImport } from './routes/_app.catalogue.index'
import { Route as AppAffairesIndexRouteImport } from './routes/_app.affaires.index'
import { Route as AppCataloguePanneauxRouteImport } from './routes/_app.catalogue.panneaux'
import { Route as AppCatalogueMatieresRouteImport } from './routes/_app.catalogue.matieres'
import { Route as AppAffairesCodeRouteImport } from './routes/_app.affaires.$code'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRoute,
} as any)
const AppMouvementsRoute = AppMouvementsRouteImport.update({
  id: '/mouvements',
  path: '/mouvements',
  getParentRoute: () => AppRoute,
} as any)
const AppFournisseursRoute = AppFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => AppRoute,
} as any)
const AppBdcRoute = AppBdcRouteImport.update({
  id: '/bdc',
  path: '/bdc',
  getParentRoute: () => AppRoute,
} as any)
const AppAffairesRoute = AppAffairesRouteImport.update({
  id: '/affaires',
  path: '/affaires',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueIndexRoute = AppCatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => AppRoute,
} as any)
const AppAffairesIndexRoute = AppAffairesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAffairesRoute,
} as any)
const AppCataloguePanneauxRoute = AppCataloguePanneauxRouteImport.update({
  id: '/catalogue/panneaux',
  path: '/catalogue/panneaux',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueMatieresRoute = AppCatalogueMatieresRouteImport.update({
  id: '/catalogue/matieres',
  path: '/catalogue/matieres',
  getParentRoute: () => AppRoute,
} as any)
const AppAffairesCodeRoute = AppAffairesCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => AppAffairesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/affaires': typeof AppAffairesRouteWithChildren
  '/bdc': typeof AppBdcRoute
  '/fournisseurs': typeof AppFournisseursRoute
  '/mouvements': typeof AppMouvementsRoute
  '/parametres': typeof AppParametresRoute
  '/affaires/$code': typeof AppAffairesCodeRoute
  '/catalogue/matieres': typeof AppCatalogueMatieresRoute
  '/catalogue/panneaux': typeof AppCataloguePanneauxRoute
  '/affaires/': typeof AppAffairesIndexRoute
  '/catalogue/': typeof AppCatalogueIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bdc': typeof AppBdcRoute
  '/fournisseurs': typeof AppFournisseursRoute
  '/mouvements': typeof AppMouvementsRoute
  '/parametres': typeof AppParametresRoute
  '/': typeof AppIndexRoute
  '/affaires/$code': typeof AppAffairesCodeRoute
  '/catalogue/matieres': typeof AppCatalogueMatieresRoute
  '/catalogue/panneaux': typeof AppCataloguePanneauxRoute
  '/affaires': typeof AppAffairesIndexRoute
  '/catalogue': typeof AppCatalogueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/affaires': typeof AppAffairesRouteWithChildren
  '/_app/bdc': typeof AppBdcRoute
  '/_app/fournisseurs': typeof AppFournisseursRoute
  '/_app/mouvements': typeof AppMouvementsRoute
  '/_app/parametres': typeof AppParametresRoute
  '/_app/': typeof AppIndexRoute
  '/_app/affaires/$code': typeof AppAffairesCodeRoute
  '/_app/catalogue/matieres': typeof AppCatalogueMatieresRoute
  '/_app/catalogue/panneaux': typeof AppCataloguePanneauxRoute
  '/_app/affaires/': typeof AppAffairesIndexRoute
  '/_app/catalogue/': typeof AppCatalogueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/affaires'
    | '/bdc'
    | '/fournisseurs'
    | '/mouvements'
    | '/parametres'
    | '/affaires/$code'
    | '/catalogue/matieres'
    | '/catalogue/panneaux'
    | '/affaires/'
    | '/catalogue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/bdc'
    | '/fournisseurs'
    | '/mouvements'
    | '/parametres'
    | '/'
    | '/affaires/$code'
    | '/catalogue/matieres'
    | '/catalogue/panneaux'
    | '/affaires'
    | '/catalogue'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/_app/affaires'
    | '/_app/bdc'
    | '/_app/fournisseurs'
    | '/_app/mouvements'
    | '/_app/parametres'
    | '/_app/'
    | '/_app/affaires/$code'
    | '/_app/catalogue/matieres'
    | '/_app/catalogue/panneaux'
    | '/_app/affaires/'
    | '/_app/catalogue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres': {
      id: '/_app/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mouvements': {
      id: '/_app/mouvements'
      path: '/mouvements'
      fullPath: '/mouvements'
      preLoaderRoute: typeof AppMouvementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fournisseurs': {
      id: '/_app/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof AppFournisseursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bdc': {
      id: '/_app/bdc'
      path: '/bdc'
      fullPath: '/bdc'
      preLoaderRoute: typeof AppBdcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affaires': {
      id: '/_app/affaires'
      path: '/affaires'
      fullPath: '/affaires'
      preLoaderRoute: typeof AppAffairesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue/': {
      id: '/_app/catalogue/'
      path: '/catalogue'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof AppCatalogueIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affaires/': {
      id: '/_app/affaires/'
      path: '/'
      fullPath: '/affaires/'
      preLoaderRoute: typeof AppAffairesIndexRouteImport
      parentRoute: typeof AppAffairesRoute
    }
    '/_app/catalogue/panneaux': {
      id: '/_app/catalogue/panneaux'
      path: '/catalogue/panneaux'
      fullPath: '/catalogue/panneaux'
      preLoaderRoute: typeof AppCataloguePanneauxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue/matieres': {
      id: '/_app/catalogue/matieres'
      path: '/catalogue/matieres'
      fullPath: '/catalogue/matieres'
      preLoaderRoute: typeof AppCatalogueMatieresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affaires/$code': {
      id: '/_app/affaires/$code'
      path: '/$code'
      fullPath: '/affaires/$code'
      preLoaderRoute: typeof AppAffairesCodeRouteImport
      parentRoute: typeof AppAffairesRoute
    }
  }
}

interface AppAffairesRouteChildren {
  AppAffairesCodeRoute: typeof AppAffairesCodeRoute
  AppAffairesIndexRoute: typeof AppAffairesIndexRoute
}

const AppAffairesRouteChildren: AppAffairesRouteChildren = {
  AppAffairesCodeRoute: AppAffairesCodeRoute,
  AppAffairesIndexRoute: AppAffairesIndexRoute,
}

const AppAffairesRouteWithChildren = AppAffairesRoute._addFileChildren(
  AppAffairesRouteChildren,
)

interface AppRouteChildren {
  AppAffairesRoute: typeof AppAffairesRouteWithChildren
  AppBdcRoute: typeof AppBdcRoute
  AppFournisseursRoute: typeof AppFournisseursRoute
  AppMouvementsRoute: typeof AppMouvementsRoute
  AppParametresRoute: typeof AppParametresRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCatalogueMatieresRoute: typeof AppCatalogueMatieresRoute
  AppCataloguePanneauxRoute: typeof AppCataloguePanneauxRoute
  AppCatalogueIndexRoute: typeof AppCatalogueIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAffairesRoute: AppAffairesRouteWithChildren,
  AppBdcRoute: AppBdcRoute,
  AppFournisseursRoute: AppFournisseursRoute,
  AppMouvementsRoute: AppMouvementsRoute,
  AppParametresRoute: AppParametresRoute,
  AppIndexRoute: AppIndexRoute,
  AppCatalogueMatieresRoute: AppCatalogueMatieresRoute,
  AppCataloguePanneauxRoute: AppCataloguePanneauxRoute,
  AppCatalogueIndexRoute: AppCatalogueIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
