/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppParametresRouteImport } from './routes/_app.parametres'
import { Route as AppMouvementsRouteImport } from './routes/_app.mouvements'
import { Route as AppFournisseursRouteImport } from './routes/_app.fournisseurs'
import { Route as AppBdcRouteImport } from './routes/_app.bdc'
import { Route as AppAffairesRouteImport } from './routes/_app.affaires'
import { Route as AppCatalogueIndexRouteImport } from './routes/_app.catalogue.index'
import { Route as AppCataloguePanneauxRouteImport } from './routes/_app.catalogue.panneaux'
import { Route as AppCatalogueMatieresRouteImport } from './routes/_app.catalogue.matieres'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRoute,
} as any)
const AppMouvementsRoute = AppMouvementsRouteImport.update({
  id: '/mouvements',
  path: '/mouvements',
  getParentRoute: () => AppRoute,
} as any)
const AppFournisseursRoute = AppFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => AppRoute,
} as any)
const AppBdcRoute = AppBdcRouteImport.update({
  id: '/bdc',
  path: '/bdc',
  getParentRoute: () => AppRoute,
} as any)
const AppAffairesRoute = AppAffairesRouteImport.update({
  id: '/affaires',
  path: '/affaires',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueIndexRoute = AppCatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => AppRoute,
} as any)
const AppCataloguePanneauxRoute = AppCataloguePanneauxRouteImport.update({
  id: '/catalogue/panneaux',
  path: '/catalogue/panneaux',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueMatieresRoute = AppCatalogueMatieresRouteImport.update({
  id: '/catalogue/matieres',
  path: '/catalogue/matieres',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/affaires': typeof AppAffairesRoute
  '/bdc': typeof AppBdcRoute
  '/fournisseurs': typeof AppFournisseursRoute
  '/mouvements': typeof AppMouvementsRoute
  '/parametres': typeof AppParametresRoute
  '/catalogue/matieres': typeof AppCatalogueMatieresRoute
  '/catalogue/panneaux': typeof AppCataloguePanneauxRoute
  '/catalogue/': typeof AppCatalogueIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/affaires': typeof AppAffairesRoute
  '/bdc': typeof AppBdcRoute
  '/fournisseurs': typeof AppFournisseursRoute
  '/mouvements': typeof AppMouvementsRoute
  '/parametres': typeof AppParametresRoute
  '/': typeof AppIndexRoute
  '/catalogue/matieres': typeof AppCatalogueMatieresRoute
  '/catalogue/panneaux': typeof AppCataloguePanneauxRoute
  '/catalogue': typeof AppCatalogueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/affaires': typeof AppAffairesRoute
  '/_app/bdc': typeof AppBdcRoute
  '/_app/fournisseurs': typeof AppFournisseursRoute
  '/_app/mouvements': typeof AppMouvementsRoute
  '/_app/parametres': typeof AppParametresRoute
  '/_app/': typeof AppIndexRoute
  '/_app/catalogue/matieres': typeof AppCatalogueMatieresRoute
  '/_app/catalogue/panneaux': typeof AppCataloguePanneauxRoute
  '/_app/catalogue/': typeof AppCatalogueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/affaires'
    | '/bdc'
    | '/fournisseurs'
    | '/mouvements'
    | '/parametres'
    | '/catalogue/matieres'
    | '/catalogue/panneaux'
    | '/catalogue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/affaires'
    | '/bdc'
    | '/fournisseurs'
    | '/mouvements'
    | '/parametres'
    | '/'
    | '/catalogue/matieres'
    | '/catalogue/panneaux'
    | '/catalogue'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/affaires'
    | '/_app/bdc'
    | '/_app/fournisseurs'
    | '/_app/mouvements'
    | '/_app/parametres'
    | '/_app/'
    | '/_app/catalogue/matieres'
    | '/_app/catalogue/panneaux'
    | '/_app/catalogue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres': {
      id: '/_app/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mouvements': {
      id: '/_app/mouvements'
      path: '/mouvements'
      fullPath: '/mouvements'
      preLoaderRoute: typeof AppMouvementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fournisseurs': {
      id: '/_app/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof AppFournisseursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bdc': {
      id: '/_app/bdc'
      path: '/bdc'
      fullPath: '/bdc'
      preLoaderRoute: typeof AppBdcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affaires': {
      id: '/_app/affaires'
      path: '/affaires'
      fullPath: '/affaires'
      preLoaderRoute: typeof AppAffairesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue/': {
      id: '/_app/catalogue/'
      path: '/catalogue'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof AppCatalogueIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue/panneaux': {
      id: '/_app/catalogue/panneaux'
      path: '/catalogue/panneaux'
      fullPath: '/catalogue/panneaux'
      preLoaderRoute: typeof AppCataloguePanneauxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue/matieres': {
      id: '/_app/catalogue/matieres'
      path: '/catalogue/matieres'
      fullPath: '/catalogue/matieres'
      preLoaderRoute: typeof AppCatalogueMatieresRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAffairesRoute: typeof AppAffairesRoute
  AppBdcRoute: typeof AppBdcRoute
  AppFournisseursRoute: typeof AppFournisseursRoute
  AppMouvementsRoute: typeof AppMouvementsRoute
  AppParametresRoute: typeof AppParametresRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCatalogueMatieresRoute: typeof AppCatalogueMatieresRoute
  AppCataloguePanneauxRoute: typeof AppCataloguePanneauxRoute
  AppCatalogueIndexRoute: typeof AppCatalogueIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAffairesRoute: AppAffairesRoute,
  AppBdcRoute: AppBdcRoute,
  AppFournisseursRoute: AppFournisseursRoute,
  AppMouvementsRoute: AppMouvementsRoute,
  AppParametresRoute: AppParametresRoute,
  AppIndexRoute: AppIndexRoute,
  AppCatalogueMatieresRoute: AppCatalogueMatieresRoute,
  AppCataloguePanneauxRoute: AppCataloguePanneauxRoute,
  AppCatalogueIndexRoute: AppCatalogueIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
