// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * Contexte injecté par `requireSupabaseAuth` dans les server functions.
 * Utiliser ce type pour typer le paramètre `context` au lieu de `any`.
 *
 * Exemple :
 *   .handler(async ({ context }: { context: AuthedContext }) => { ... })
 */
export type AuthedContext = {
  supabase: SupabaseClient<Database>;
  userId: string;
  claims: Record<string, unknown> & { sub: string };
};

export const requireSupabaseAuth = createMiddleware({ type: "function" })
  .client(async ({ next }) => {
    // Forward the current Supabase session token to the server function
    // so the server-side middleware can validate it.
    let headers: Record<string, string> = {};
    if (typeof window !== "undefined") {
      try {
        // Lazy import to avoid pulling the browser client into SSR-only paths.
        const { supabase } = await import("./client");
        const { data } = await supabase.auth.getSession();
        const token = data.session?.access_token;
        if (token) {
          headers = { Authorization: `Bearer ${token}` };
        }
      } catch {
        // ignore — server middleware will reject with 401 if needed
      }
    }
    return next({ sendContext: {}, headers });
  })
  .server(async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      throw new Response(
        "Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY are set.",
        { status: 500 },
      );
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Response("Unauthorized: No request headers available", { status: 401 });
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Response("Unauthorized: No authorization header provided", { status: 401 });
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Response("Unauthorized: Only Bearer tokens are supported", { status: 401 });
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Response("Unauthorized: No token provided", { status: 401 });
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Response("Unauthorized: Invalid token", { status: 401 });
    }

    if (!data.claims.sub) {
      throw new Response("Unauthorized: No user ID found in token", { status: 401 });
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  });

