// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function getSupabaseServerEnv() {
  return {
    supabaseUrl: process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL,
    serviceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY,
  };
}

function createSupabaseAdminClient() {
  const { supabaseUrl, serviceRoleKey } = getSupabaseServerEnv();

  if (!supabaseUrl || !serviceRoleKey) {
    throw new Error(
      "Les opérations d'administration ne sont pas disponibles dans cette preview. Testez-les sur l'URL publiée.",
    );
  }

  return createClient<Database>(supabaseUrl, serviceRoleKey, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

type SupabaseAdminClient = ReturnType<typeof createSupabaseAdminClient>;

let _supabaseAdmin: SupabaseAdminClient | undefined;

export function getSupabaseAdminClient(): SupabaseAdminClient | null {
  const { supabaseUrl, serviceRoleKey } = getSupabaseServerEnv();
  if (!supabaseUrl || !serviceRoleKey) return null;

  if (!_supabaseAdmin) {
    _supabaseAdmin = createSupabaseAdminClient();
  }

  return _supabaseAdmin;
}

export function requireSupabaseAdminClient(feature = "Cette action"): SupabaseAdminClient {
  const client = getSupabaseAdminClient();
  if (!client) {
    throw new Error(`${feature} n'est pas disponible dans cette preview. Testez sur l'URL publiée.`);
  }
  return client;
}

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as SupabaseAdminClient, {
  get(_, prop, receiver) {
    const client = requireSupabaseAdminClient();
    return Reflect.get(client, prop, receiver);
  },
});
